### ISSUE TITLE
FEATURE-1 - Implement a table of contents for lists

### ISSUE THREAD

**Issue by skinet2009** [rvoskanyan/TODO-Planner#1]
Добавить оглавление.
Это компонент, который отображает список ToDo-листов.
Должны быть кнопки для быстрого удаления каждого списка. Так же, кнопка добавления нового списка.
При клике на название списка, открывается этот самый список.

В качестве названия списка - его название или дата создания.
По умолчанию, в поле названия проставляется дата создания. При желании, название можно отредактировать, когда список открыт на редактирование.
Т.е. ожидается следующее поведение:
- создали список, в его названии проставилась дата создания.
- нажав на само поле названия - переходим в его редактирование. Можем вводить любой текст. Так же доступна кнопка выбора даты, при выборе даты весь текст меняется на дату.

Дополнительно, у каждого todo-листа должна храниться информация как о дате и времени создания списка, так и о дате и времени последнего редактирования.

**Comment by rvoskanyan** [comment]
Необходимо 5 часов
