### ISSUE TITLE
FEATURE-3 - Connect eslint-config-airbnb and fix codestyle

### ISSUE THREAD

**Issue by skinet2009** [rvoskanyan/TODO-Planner#3]
https://github.com/airbnb/javascript

**Comment by rvoskanyan** [comment]
Необходимо 1 час

**Comment by skinet2009** [comment]
Добавить следующие правила:
- пустая строка после объявления переменных (error)
- разрешить только console.info, console.error (warn)
- запретить однострочный if (error)
- пустая строка после блока кода - if, for, while, etc. (warn)
- перед return пустая строка, кроме однострочного блока (warn)

**Comment by rvoskanyan** [comment]
- [ ] - пустая строка после объявления переменных (error)
- [ ] - разрешить только console.info, console.error (warn)
- [ ] - запретить однострочный if (error)
- [ ] - пустая строка после блока кода - if, for, while, etc. (warn)
- [ ] - перед return пустая строка, кроме однострочного блока (warn)
